// Language and Currency Configuration
export const LANGUAGES = {
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    rtl: false,
    translations: {
      // Header
      invoice: 'Invoice',
      currentDate: 'Current Date',
      invoiceNumber: 'Invoice Number',
      cashierName: 'Cashier Name',
      customerName: 'Customer Name',
      
      // Items
      itemName: 'Item Name',
      quantity: 'Qty',
      price: 'Price',
      action: 'Action',
      addItem: 'Add Item',
      delete: 'Delete',
      
      // Summary
      subtotal: 'Subtotal',
      discount: 'Discount (%)',
      tax: 'Tax (%)',
      total: 'Total',
      
      // Actions
      reviewInvoice: 'Review Invoice',
      saveAsPDF: 'Save as PDF',
      print: 'Print',
      addNextInvoice: 'Add Next Invoice',
      close: 'Close',
      
      // Settings
      settings: 'Settings',
      language: 'Language',
      currency: 'Currency',
      theme: 'Theme',
      analytics: 'Analytics',
      
      // Analytics
      monthlyStats: 'Monthly Statistics',
      yearlyStats: 'Yearly Statistics',
      totalEarnings: 'Total Earnings',
      totalInvoices: 'Total Invoices',
      averageInvoice: 'Average Invoice',
      thisMonth: 'This Month',
      thisYear: 'This Year',
      
      // Themes
      modern: 'Modern',
      classic: 'Classic',
      minimal: 'Minimal',
      dark: 'Dark'
    }
  },
  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    rtl: false,
    translations: {
      invoice: 'Factura',
      currentDate: 'Fecha Actual',
      invoiceNumber: 'Número de Factura',
      cashierName: 'Nombre del Cajero',
      customerName: 'Nombre del Cliente',
      itemName: 'Nombre del Artículo',
      quantity: 'Cant.',
      price: 'Precio',
      action: 'Acción',
      addItem: 'Agregar Artículo',
      delete: 'Eliminar',
      subtotal: 'Subtotal',
      discount: 'Descuento (%)',
      tax: 'Impuesto (%)',
      total: 'Total',
      reviewInvoice: 'Revisar Factura',
      saveAsPDF: 'Guardar como PDF',
      print: 'Imprimir',
      addNextInvoice: 'Agregar Siguiente Factura',
      close: 'Cerrar',
      settings: 'Configuración',
      language: 'Idioma',
      currency: 'Moneda',
      theme: 'Tema',
      analytics: 'Análisis',
      monthlyStats: 'Estadísticas Mensuales',
      yearlyStats: 'Estadísticas Anuales',
      totalEarnings: 'Ganancias Totales',
      totalInvoices: 'Facturas Totales',
      averageInvoice: 'Factura Promedio',
      thisMonth: 'Este Mes',
      thisYear: 'Este Año',
      modern: 'Moderno',
      classic: 'Clásico',
      minimal: 'Minimalista',
      dark: 'Oscuro'
    }
  },
  fr: {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
    rtl: false,
    translations: {
      invoice: 'Facture',
      currentDate: 'Date Actuelle',
      invoiceNumber: 'Numéro de Facture',
      cashierName: 'Nom du Caissier',
      customerName: 'Nom du Client',
      itemName: 'Nom de l\'Article',
      quantity: 'Qté',
      price: 'Prix',
      action: 'Action',
      addItem: 'Ajouter Article',
      delete: 'Supprimer',
      subtotal: 'Sous-total',
      discount: 'Remise (%)',
      tax: 'Taxe (%)',
      total: 'Total',
      reviewInvoice: 'Réviser Facture',
      saveAsPDF: 'Sauvegarder en PDF',
      print: 'Imprimer',
      addNextInvoice: 'Ajouter Facture Suivante',
      close: 'Fermer',
      settings: 'Paramètres',
      language: 'Langue',
      currency: 'Devise',
      theme: 'Thème',
      analytics: 'Analytique',
      monthlyStats: 'Statistiques Mensuelles',
      yearlyStats: 'Statistiques Annuelles',
      totalEarnings: 'Gains Totaux',
      totalInvoices: 'Factures Totales',
      averageInvoice: 'Facture Moyenne',
      thisMonth: 'Ce Mois',
      thisYear: 'Cette Année',
      modern: 'Moderne',
      classic: 'Classique',
      minimal: 'Minimal',
      dark: 'Sombre'
    }
  },
  ar: {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
    rtl: true,
    translations: {
      invoice: 'فاتورة',
      currentDate: 'التاريخ الحالي',
      invoiceNumber: 'رقم الفاتورة',
      cashierName: 'اسم الكاشير',
      customerName: 'اسم العميل',
      itemName: 'اسم الصنف',
      quantity: 'الكمية',
      price: 'السعر',
      action: 'إجراء',
      addItem: 'إضافة صنف',
      delete: 'حذف',
      subtotal: 'المجموع الفرعي',
      discount: 'الخصم (%)',
      tax: 'الضريبة (%)',
      total: 'الإجمالي',
      reviewInvoice: 'مراجعة الفاتورة',
      saveAsPDF: 'حفظ كـ PDF',
      print: 'طباعة',
      addNextInvoice: 'إضافة فاتورة تالية',
      close: 'إغلاق',
      settings: 'الإعدادات',
      language: 'اللغة',
      currency: 'العملة',
      theme: 'السمة',
      analytics: 'التحليلات',
      monthlyStats: 'إحصائيات شهرية',
      yearlyStats: 'إحصائيات سنوية',
      totalEarnings: 'إجمالي الأرباح',
      totalInvoices: 'إجمالي الفواتير',
      averageInvoice: 'متوسط الفاتورة',
      thisMonth: 'هذا الشهر',
      thisYear: 'هذا العام',
      modern: 'حديث',
      classic: 'كلاسيكي',
      minimal: 'بسيط',
      dark: 'داكن'
    }
  },
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    rtl: false,
    translations: {
      invoice: '发票',
      currentDate: '当前日期',
      invoiceNumber: '发票号码',
      cashierName: '收银员姓名',
      customerName: '客户姓名',
      itemName: '商品名称',
      quantity: '数量',
      price: '价格',
      action: '操作',
      addItem: '添加商品',
      delete: '删除',
      subtotal: '小计',
      discount: '折扣 (%)',
      tax: '税费 (%)',
      total: '总计',
      reviewInvoice: '预览发票',
      saveAsPDF: '保存为PDF',
      print: '打印',
      addNextInvoice: '添加下一张发票',
      close: '关闭',
      settings: '设置',
      language: '语言',
      currency: '货币',
      theme: '主题',
      analytics: '分析',
      monthlyStats: '月度统计',
      yearlyStats: '年度统计',
      totalEarnings: '总收入',
      totalInvoices: '总发票数',
      averageInvoice: '平均发票',
      thisMonth: '本月',
      thisYear: '今年',
      modern: '现代',
      classic: '经典',
      minimal: '简约',
      dark: '深色'
    }
  }
};

export const CURRENCIES = {
  USD: { symbol: '$', name: 'US Dollar', code: 'USD' },
  EUR: { symbol: '€', name: 'Euro', code: 'EUR' },
  GBP: { symbol: '£', name: 'British Pound', code: 'GBP' },
  INR: { symbol: '₹', name: 'Indian Rupee', code: 'INR' },
  JPY: { symbol: '¥', name: 'Japanese Yen', code: 'JPY' },
  CNY: { symbol: '¥', name: 'Chinese Yuan', code: 'CNY' },
  SAR: { symbol: 'ر.س', name: 'Saudi Riyal', code: 'SAR' },
  AED: { symbol: 'د.إ', name: 'UAE Dirham', code: 'AED' },
  CAD: { symbol: 'C$', name: 'Canadian Dollar', code: 'CAD' },
  AUD: { symbol: 'A$', name: 'Australian Dollar', code: 'AUD' }
};

export const THEMES = {
  modern: {
    name: 'modern',
    colors: {
      primary: 'bg-blue-600',
      primaryHover: 'hover:bg-blue-700',
      secondary: 'bg-gray-100',
      accent: 'bg-blue-50',
      text: 'text-gray-900',
      textSecondary: 'text-gray-600',
      border: 'border-gray-300',
      background: 'bg-white',
      inputBackground: 'bg-white',
      inputText: 'text-gray-900',
      inputBorder: 'border-gray-300'
    }
  },
  classic: {
    name: 'classic',
    colors: {
      primary: 'bg-green-600',
      primaryHover: 'hover:bg-green-700',
      secondary: 'bg-green-50',
      accent: 'bg-green-100',
      text: 'text-gray-800',
      textSecondary: 'text-gray-600',
      border: 'border-green-300',
      background: 'bg-green-50',
      inputBackground: 'bg-white',
      inputText: 'text-gray-800',
      inputBorder: 'border-green-300'
    }
  },
  minimal: {
    name: 'minimal',
    colors: {
      primary: 'bg-gray-800',
      primaryHover: 'hover:bg-gray-900',
      secondary: 'bg-gray-50',
      accent: 'bg-gray-100',
      text: 'text-gray-900',
      textSecondary: 'text-gray-500',
      border: 'border-gray-200',
      background: 'bg-white',
      inputBackground: 'bg-white',
      inputText: 'text-gray-900',
      inputBorder: 'border-gray-200'
    }
  },
  dark: {
    name: 'dark',
    colors: {
      primary: 'bg-purple-600',
      primaryHover: 'hover:bg-purple-700',
      secondary: 'bg-gray-800',
      accent: 'bg-gray-700',
      text: 'text-gray-100',
      textSecondary: 'text-gray-300',
      border: 'border-gray-600',
      background: 'bg-gray-900',
      inputBackground: 'bg-gray-800',
      inputText: 'text-gray-100',
      inputBorder: 'border-gray-600'
    }
  }
};
